function AWSDRInputMapIdent = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  AWSDRINPUTMAPIDENT = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  AWSDRINPUTMAPIDENT = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  AWSDRINPUTMAPIDENT = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  AWSDRInputMapIdent = importfile("/Users/mk/Workspace/GitLab/pFaces-OmegaThreads/examples/deepracer/InMap_ident/Steering/AWS_DR_InputMapIdent.xlsx", "Steering Input Map", [8, 48]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-May-2021 20:49:31

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [8, 48];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":E" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Var1", "min", "Var3", "Var4", "VarName5"];
opts.SelectedVariableNames = ["min", "VarName5"];
opts.VariableTypes = ["char", "double", "char", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var3", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var3", "Var4"], "EmptyFieldRule", "auto");

% Import the data
AWSDRInputMapIdent = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":E" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    AWSDRInputMapIdent = [AWSDRInputMapIdent; tb]; %#ok<AGROW>
end

end