# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Berlin"
        
      - name: Install stuff
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends apt-utils
          sudo apt-get upgrade -y
          sudo apt-get install -y cmake wget git unzip build-essential libcpprest-dev opencl-c-headers  opencl-clhpp-headers ocl-icd-opencl-dev clinfo oclgrind cmake

      - name: Install pFaces
        run: |
          mkdir pfaces
          cd pfaces
          wget https://github.com/parallall/pFaces/releases/download/Release_1.2.0d/pFaces-1.2.0-Ubuntu18.04.zip
          unzip pFaces-1.2.0-Ubuntu18.04.zip
          sudo sh install.sh
          
      - name: Install GraalVM (20.1 AMD64)
        run: |
          wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
          echo '18f2dc19652c66ccd5bd54198e282db645ea894d67357bf5e4121a9392fc9394 graalvm-ce-java11-linux-amd64-20.1.0.tar.gz' | sha256sum --check
          tar -zxvf graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
          rm graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
          mv graalvm-ce-java11-20.1.0 /opt/
          
      - name: Update Env Vars for Java
        run: |
          echo "PATH=/opt/graalvm-ce-java11-20.1.0/bin/:${{ env.PATH }}" >> $GITHUB_ENV
          echo "JAVA_HOME=/opt/graalvm-ce-java11-20.1.0/" >> $GITHUB_ENV
          
      - name: Install Native-Image
        run: gu install native-image
        
      - name: Clone OmegaThreads and install OWL
        run: |
          git clone --depth=1 https://github.com/mkhaled87/pFaces-OmegaThreads
          cd ./pFaces-OmegaThreads/kernel-driver/lib/ltl2dpa
          git clone --depth 1 --branch release-20.06.00 https://gitlab.lrz.de/i7/owl
          cd owl
          ./gradlew clean
          ./gradlew distZip -x javadoc -Pdisable-pandoc
          sudo cp ./build/native-library/libowl.so /usr/lib/
          
      - name: Build OmegaThreads
        run: |
          cd ./pFaces-OmegaThreads/
          export PFACES_SDK_ROOT=$PWD/../pfaces/pfaces-sdk/
          sh build.sh
          
