# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Make Ubuntu Ready for time zone 
        run: sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
        
      - name: Install stuff
        run: 
          sudo apt-get update
          apt-get install -y --no-install-recommends apt-util
          apt-get upgrade -y
          apt-get install -y cmake wget git unzip build-essential libcpprest-dev opencl-c-headers  opencl-clhpp-headers ocl-icd-opencl-dev clinfo oclgrind cmake

      - name: Install pFaces
        run: 
          mkdir pfaces
          cd pfaces
          wget https://github.com/parallall/pFaces/releases/download/Release_1.2.0d/pFaces-1.2.0-Ubuntu18.04.zip
          unzip pFaces-1.2.0-Ubuntu18.04.zip
          sudo sh install.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
